/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as TradesNewRouteImport } from './routes/trades.new'
import { Route as TradesTradeIdRouteImport } from './routes/trades.$tradeId'
import { Route as ReviewsNewRouteImport } from './routes/reviews.new'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews.$reviewId'

const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesNewRoute = TradesNewRouteImport.update({
  id: '/trades/new',
  path: '/trades/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeIdRoute = TradesTradeIdRouteImport.update({
  id: '/trades/$tradeId',
  path: '/trades/$tradeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/trades/new': typeof TradesNewRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/trades/new': typeof TradesNewRoute
  '/reviews': typeof ReviewsIndexRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/trades/new': typeof TradesNewRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/calendar'
    | '/reviews/$reviewId'
    | '/reviews/new'
    | '/trades/$tradeId'
    | '/trades/new'
    | '/reviews/'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/calendar'
    | '/reviews/$reviewId'
    | '/reviews/new'
    | '/trades/$tradeId'
    | '/trades/new'
    | '/reviews'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/analytics'
    | '/calendar'
    | '/reviews/$reviewId'
    | '/reviews/new'
    | '/trades/$tradeId'
    | '/trades/new'
    | '/reviews/'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  TradesTradeIdRoute: typeof TradesTradeIdRoute
  TradesNewRoute: typeof TradesNewRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/new': {
      id: '/trades/new'
      path: '/trades/new'
      fullPath: '/trades/new'
      preLoaderRoute: typeof TradesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$tradeId': {
      id: '/trades/$tradeId'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof TradesTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  TradesTradeIdRoute: TradesTradeIdRoute,
  TradesNewRoute: TradesNewRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
